#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

#define FRONTIER_MONS_HIGH_TIER     0 // Mons above this point can only appear > level 50

#define NUM_FRONTIER_MONS           0

#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
